version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3309"
    volumes:
      - mysql_data:/var/lib/mysql

  init:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./init.sh:/init.sh

volumes:
  mysql_data:
